# Generated by Django 2.1.5 on 2019-01-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=50)),
                ('useremail', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('userpassword', models.CharField(max_length=50)),
            ],
        ),
    ]
